# -*- coding: utf-8 -*-
"""GDSC_Week9_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qtSAvzGN9iu-6in1iIAhOWLUiMkLnxaR
"""

!pip install sentence-transformers

import pandas as pd
from sentence_transformers import SentenceTransformer

# SentenceTransformer 모델 로드
model = SentenceTransformer('klue/roberta-large')  # 모델명에 원하는 모델명을 입력해야 합니다.

# 엑셀 파일 읽기
file_path = 'Question.xlsx'
df = pd.read_excel('/content/Qusetion.xlsx')

# '질문 (Query)' 열의 내용을 가져와서 임베딩 처리
queries = df['질문 (Query)'].tolist()

# 각 질문을 임베딩하여 리스트에 저장
embeddings = model.encode(queries)

# 임베딩된 결과를 새로운 열로 추가
df['embedding_vector'] = embeddings.tolist()

# 수정된 데이터프레임을 새로운 엑셀 파일로 저장
output_file_path = 'Question_with_Embeddings_ST.xlsx'
df.to_excel(output_file_path, index=False)

import torch
tensor_embeddings= torch.tensor(embeddings)

print(tensor_embeddings)



















